[package]
# Semantic Versioning is used: https://semver.org/
version = "1.0.0"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["Microsoft"]

# The title and description fields are primarily for displaying extension info in UI
title = "Azure ADT"
description="A simple python extension example to use as a starting point for your extensions."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Azure"

# Keywords for the extension
keywords = ["kit", "azure", "adt"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/icon.png"

# Use omni.ui to build simple UI

[settings]
exts."msft.ext.adt".zoom.inout_on_prim_selection = true
exts."msft.ext.adt".zoom.in_value = 0.45
exts."msft.ext.adt".zoom.show_twin_raw_data_at_app_panel = true
exts."msft.ext.adt".zoom.show_twin_viewport_popup_wehen_selected = true

[dependencies]
"omni.kit.uiapp" = {}
"msft.ext.viewport_widgets_manager" = {}

# Main python module this extension provides, it will be publicly available as "import msft.adt_ext".
[[python.module]]
name = "msft.ext.adt"


[python.pipapi]
requirements = [
    #"cffi",
    #"wheel",
    #"pipfile",




    #"signalrcore",
    #"azure-digitaltwins-core",
    #"azure-identity"
]
use_online_index = true

[[test]]
# Extra dependencies only to be used during test run
dependencies = [
    "omni.kit.ui_test" # UI testing extension
]
